# Generated by Django 5.1.7 on 2025-03-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dogs',
            new_name='Dog',
        ),
    ]
