# Generated by Django 5.1.7 on 2025-03-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cats',
            new_name='Cat',
        ),
    ]
